# Generated by Django 5.1 on 2024-09-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
