# Generated by Django 5.1 on 2024-09-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
