# Generated by Django 5.1 on 2024-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationevent',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
