# Generated by Django 5.1 on 2024-09-28 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_donationevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
