# Generated by Django 5.1 on 2024-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_donationevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='blood_donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
