# Generated by Django 5.1 on 2024-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorregistrationmodel',
            old_name='number',
            new_name='mobaile_no',
        ),
    ]
