# Generated by Django 5.1 on 2024-09-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_number_donorregistrationmodel_mobaile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorProfile',
        ),
    ]
