# Generated by Django 5.1 on 2024-09-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_donorprofile_image'),
        ('events', '0004_delete_aboutus_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='reciver_blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.donationevent'),
        ),
    ]
