# Generated by Django 5.1 on 2024-09-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_donorprofile_reciver_blood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='reciver_blood',
        ),
    ]
