# Generated by Django 5.1 on 2024-09-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_donorprofile_reciver_blood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_donation_date',
        ),
    ]
