# Generated by Django 5.1 on 2024-09-28 21:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_donorprofile_last_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='blood_donation_count',
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Product_images'),
        ),
    ]
