# Generated by Django 5.1 on 2024-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_donorprofile_blood_donation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='image',
            field=models.ImageField(upload_to='accounts/media/images'),
        ),
    ]
