# Generated by Django 5.1 on 2024-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_donorprofile_name_alter_donorprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='mobaile_no',
            field=models.PositiveIntegerField(),
        ),
    ]
