# Generated by Django 5.1 on 2024-10-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_donorprofile_age_alter_donorprofile_mobaile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorregistrationmodel',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donorregistrationmodel',
            name='mobaile_no',
            field=models.PositiveIntegerField(),
        ),
    ]
