# Generated by Django 5.1 on 2024-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_donorprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
