# Generated by Django 5.1 on 2024-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_donorprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='accounts/media/images'),
            preserve_default=False,
        ),
    ]
