# Generated by Django 5.1 on 2024-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_donorprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='image',
            field=models.ImageField(upload_to='accounts/media/images'),
        ),
    ]
