# Generated by Django 5.1 on 2024-10-03 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_releted', '0002_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='DonorBlogPost',
        ),
    ]
