# Generated by Django 5.1.2 on 2024-10-10 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_releted', '0006_subscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorblogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
